version: '3'

services:
  postgres:
    container_name: my-postgres-container
    build: 
      context: ./dockerFiles
      dockerfile: Dockerfile-postgres
    environment:
      POSTGRES_USER: Snusmumric
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - /S/Repository/Microservices/PlatformService/PlatformService/bin/Debug/net7.0/DBFiles/Postgre:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4
    build: 
      context: ./dockerFiles
      dockerfile: Dockerfile-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-root@root.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  elasticsearch:
    container_name: elasticsearch
    build: 
      context: ./dockerFiles
      dockerfile: Dockerfile-elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /S/Repository/Microservices/PlatformService/PlatformService/bin/Debug/net7.0/Logs/elasticsearch-data:/usr/share/elasticsearch/data
      - /S/Repository/Microservices/PlatformService/PlatformService/bin/Debug/net7.0/Logs/elasticsearch-logs:/usr/share/elasticsearch/logs
    restart: unless-stopped

  kibana:
    container_name: kibana
    build: 
      context: ./dockerFiles
      dockerfile: Dockerfile-kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - postgres
    restart: unless-stopped

  logstash:
    container_name: logstash
    build: 
      context: ./dockerFiles
      dockerfile: Dockerfile-logstash
    ports:
      - "5044:5044"
    volumes:
      - ./LogStashConf:/usr/share/logstash/LogStashConf
      - /S/Repository/Docker/LogStash/Files/logstash/logs:/usr/share/logstash/logs
    depends_on:
      - elasticsearch
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local
